## Assignment 10
## Data Analytics III

Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset.
Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall on the given dataset. Provide the codes with outputs and explain everything that you do in this step.

### Importing Libraries 

In [36]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score, precision_score,recall_score
from sklearn import preprocessing

### Getting the Dataset 
##### We are going to work on the Titanic Data set imported from ../Datasets/Iris.csv

In [37]:
df = pd.read_csv("../Datasets/Iris.csv")

##### print the data to check if the data imported properly
###### Data dimension -

In [38]:
df.shape

(150, 6)

###### Data Size -

In [39]:
df.size

900

###### Description of the data frame -

In [40]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

###### Data types of different columns -

In [41]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

###### printing first 5 rows -

In [42]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Checking of NULL values

In [43]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

### Checking of duplicate values

In [44]:
df.duplicated().sum()

0

#### Encoding the Species data which will be our target set

In [45]:
label_encoder = preprocessing.LabelEncoder()
df['Species'] = label_encoder.fit_transform(df['Species'])
df['Species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

### Data Splitting
here What we expect is that we will have all the other parameters and one of the parameter will be guessed from the other features 

So let ```X``` be features that we have the data about 
and let ```Y``` be the target varible that we will predict about 

In [46]:
X = df.drop(['Id','Species'],axis = 1)
y = df['Species']

Now we need to split the data in the training and testing datasets
, this can be done with the ```train_test_split()```

#### Parameters 
* X: Feature array.
* y: Target array.
* test_size: The proportion of the dataset to include in the test split. For example, test_size=0.2 means that 20% of the data will be used for testing, and 80% for training.
* random_state: An optional parameter to seed the random number generator for reproducibility. Setting a specific random_state ensures that the same split is obtained each time the code is run.

#### Output
* X_train: Features for the training set.
* X_test: Features for the testing set.
* y_train: Target values for the training set.
* y_test: Target values for the testing set.


In [47]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.2,random_state=25 )

### Naive Bayes Model

In [48]:
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

Accuracy

In [49]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9333333333333333


Confusion Matrix

In [50]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[ 9,  0,  0],
       [ 0, 12,  1],
       [ 0,  1,  7]])

Classification report

In [58]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.92      0.92      0.92        13
           2       0.88      0.88      0.88         8

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [65]:
presicion = precision_score(y_test,y_pred,average = None)
presicion

array([1.        , 0.92307692, 0.875     ])

In [66]:
accuracy = np.trace(cm) / np.sum(cm)
print("Accuracy:", accuracy)

Accuracy: 0.9333333333333333


In [72]:
recall = recall_score(y_test,y_pred,average = None)
recall

array([1.        , 0.92307692, 0.875     ])